# Generated by Django 6.0.1 on 2026-02-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=300)),
                ('option_b', models.CharField(max_length=300)),
                ('option_c', models.CharField(max_length=300)),
                ('option_d', models.CharField(max_length=300)),
                ('correct_option', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1)),
                ('category', models.CharField(choices=[('aptitude', 'Aptitude'), ('interest', 'Interest'), ('personality', 'Personality')], default='aptitude', max_length=20)),
                ('option_a_career', models.CharField(blank=True, max_length=100)),
                ('option_b_career', models.CharField(blank=True, max_length=100)),
                ('option_c_career', models.CharField(blank=True, max_length=100)),
                ('option_d_career', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('answers', models.JSONField(default=dict)),
                ('career_scores', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-taken_at'],
            },
        ),
    ]
