# Generated by Django 6.0.1 on 2026-02-22 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_career', models.CharField(max_length=200)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('description', models.TextField()),
                ('skills_required', models.TextField()),
                ('roadmap', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('assessment_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='assessments.assessmentresult')),
            ],
            options={
                'ordering': ['-confidence_score'],
            },
        ),
    ]
